#!/usr/bin/env python

import rospy
from rv_manipulation_commander import ManipulationCommander

if __name__ == '__main__':
  rospy.init_node('manipulation_commander')
  
  commander = ManipulationCommander()
  commander.run()